# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton { \n"
"border-radius: 5px; \n"
"background: white;\n"
"border: 1px solid gray;\n"
"selection-background-color: darkgray\n"
"}\n"
"QLineEdit, QComboBox {\n"
"border-radius: 5px; \n"
"background: white;\n"
"border: 1px solid gray;\n"
"selection-background-color: rgb(232, 232, 232);\n"
"}\n"
"\n"
"QLineEdit:hover, QComboBox:hover, QPushButton:hover{\n"
"background: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:pressed{\n"
"background: darkgray\n"
"}\n"
"QLineEdit:focus, QComboBox:focus {\n"
"background: rgb(240, 240, 240);\n"
"selection-color: rgb(36, 36, 36);\n"
"selection-background-color: rgb(166, 221, 255);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.table_view = QtWidgets.QTableView(self.centralwidget)
        self.table_view.setGeometry(QtCore.QRect(30, 200, 741, 361))
        self.table_view.setObjectName("table_view")
        self.line_edit_source = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_source.setGeometry(QtCore.QRect(240, 10, 341, 31))
        self.line_edit_source.setReadOnly(False)
        self.line_edit_source.setObjectName("line_edit_source")
        self.button_select_source = QtWidgets.QPushButton(self.centralwidget)
        self.button_select_source.setGeometry(QtCore.QRect(610, 10, 131, 31))
        self.button_select_source.setStyleSheet("")
        self.button_select_source.setObjectName("button_select_source")
        self.label_source = QtWidgets.QLabel(self.centralwidget)
        self.label_source.setGeometry(QtCore.QRect(40, 10, 171, 31))
        self.label_source.setStyleSheet("")
        self.label_source.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_source.setObjectName("label_source")
        self.label_pattern = QtWidgets.QLabel(self.centralwidget)
        self.label_pattern.setGeometry(QtCore.QRect(70, 50, 141, 31))
        self.label_pattern.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_pattern.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pattern.setObjectName("label_pattern")
        self.line_edit_pattern = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_pattern.setGeometry(QtCore.QRect(240, 50, 341, 31))
        self.line_edit_pattern.setReadOnly(False)
        self.line_edit_pattern.setObjectName("line_edit_pattern")
        self.button_select_pattern = QtWidgets.QPushButton(self.centralwidget)
        self.button_select_pattern.setGeometry(QtCore.QRect(610, 50, 131, 31))
        self.button_select_pattern.setObjectName("button_select_pattern")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setEnabled(True)
        self.progress_bar.setGeometry(QtCore.QRect(30, 640, 741, 21))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(30, 600, 741, 31))
        self.button_start.setObjectName("button_start")
        self.line_edit_added = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_added.setGeometry(QtCore.QRect(240, 150, 341, 31))
        self.line_edit_added.setObjectName("line_edit_added")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 131, 51))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.check_box_added = QtWidgets.QCheckBox(self.centralwidget)
        self.check_box_added.setGeometry(QtCore.QRect(600, 160, 141, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_box_added.sizePolicy().hasHeightForWidth())
        self.check_box_added.setSizePolicy(sizePolicy)
        self.check_box_added.setText("")
        self.check_box_added.setChecked(True)
        self.check_box_added.setObjectName("check_box_added")
        self.combo_box_cell = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box_cell.setGeometry(QtCore.QRect(240, 110, 341, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_box_cell.sizePolicy().hasHeightForWidth())
        self.combo_box_cell.setSizePolicy(sizePolicy)
        self.combo_box_cell.setFrame(True)
        self.combo_box_cell.setObjectName("combo_box_cell")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 140, 121, 61))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 100, 141, 51))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 561, 741, 31))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 40))
        self.tabWidget.setStyleSheet("QTabBar::tab { height: 30px; width: 120px; }\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setStyleSheet("")
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_load = QtWidgets.QAction(MainWindow)
        self.action_load.setObjectName("action_load")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu.addAction(self.action_new)
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_save_as)
        self.menu.addAction(self.action_load)
        self.menu_2.addAction(self.action_about)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExDivider"))
        self.button_select_source.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_source.setText(_translate("MainWindow", "Источник информации:"))
        self.label_pattern.setText(_translate("MainWindow", "Шаблон:"))
        self.button_select_pattern.setText(_translate("MainWindow", "Выбрать файл"))
        self.button_start.setText(_translate("MainWindow", "Начать разделять файлы"))
        self.label_2.setText(_translate("MainWindow", "Добавить текст к имени файла:"))
        self.label_3.setText(_translate("MainWindow", "Добавить порядковый номер к концу файла"))
        self.label_4.setText(_translate("MainWindow", "Использовать столбец как новые имена:"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menu_2.setTitle(_translate("MainWindow", "Прочее"))
        self.action_save.setText(_translate("MainWindow", "Сохранить"))
        self.action_load.setText(_translate("MainWindow", "Загрузить..."))
        self.action_save_as.setText(_translate("MainWindow", "Сохранить как..."))
        self.action_new.setText(_translate("MainWindow", "Новый..."))
        self.action_about.setText(_translate("MainWindow", "О программе"))
